{
  "sections": [
    {
      "data": {
        "type": "0",
        "items": [
          {
            "image": "https://www.shutterstock.com/shutterstock/photos/2470882705/display_1500/stock-vector-hello-summer-poster-or-banner-template-with-wooden-sign-summer-template-featuring-a-tropical-beach-2470882705.jpg"
          },
          {
            "image": "https://www.shutterstock.com/shutterstock/photos/2480401029/display_1500/stock-vector-offer-sunburst-ray-banner-special-offer-bubble-sticker-discount-banner-shape-sale-coupon-chat-2480401029.jpg"
          },
          {
            "image": "https://cdn.pixabay.com/photo/2020/02/28/14/53/banner-4887650_1280.jpg"
          },
          {
            "image": "https://www.shutterstock.com/shutterstock/photos/2245509829/display_1500/stock-photo-unrecognizable-kid-demonstrating-carton-placard-with-save-the-planet-inscription-during-2245509829.jpg"
          }
        ]
      }
    },
    {
      "data": {
        "type": "1",
        "items": [
          {
            "text": "Kategori 1 ",
            "subText": "Sub Text 1",
            "icon": "https://www.shutterstock.com/shutterstock/photos/2426005649/display_1500/stock-vector-supporters-sport-icon-vector-editable-stroke-linear-style-sign-for-use-web-design-logo-symbol-2426005649.jpg"
          },
          {
            "text": "Kategori 2 ",
            "subText": "Sub Text 2",
            "icon": "https://www.shutterstock.com/shutterstock/photos/2479429283/display_1500/stock-vector-online-shopping-smartphone-with-shopping-cart-icon-vector-2479429283.jpg"
          },
          {
            "text": "Kategori 3 ",
            "subText": "Sub Text 3",
            "icon": "https://www.shutterstock.com/shutterstock/photos/2477068381/display_1500/stock-vector-bull-market-simple-line-icon-2477068381.jpg"
          },
          {
            "text": "Kategori 4 ",
            "subText": "Sub Text 4",
            "icon": "https://www.shutterstock.com/shutterstock/photos/2445333029/display_1500/stock-vector-direct-marketing-icon-business-icon-2445333029.jpg"
          },
          {
            "text": "Kategori 5 ",
            "subText": "Sub Text 5",
            "icon": "https://www.shutterstock.com/shutterstock/photos/2411392503/display_1500/stock-vector-search-emerging-market-icon-outline-vector-nascent-team-platform-fintech-2411392503.jpg"
          }
        ]
      }
    },
    {
      "data": {
        "type": "2",
        "items": [
          {
            "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=3484&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "badges": [
              {
                "text": "badge1",
                "icon": "https://i.hizliresim.com/rawfdju.png"
              },
              {
                "text": "badge2",
                "icon": "https://i.hizliresim.com/2psw5ds.png"
              }
            ],
            "leftIcon": "icon1",
            "rightIcon": "icon2",
            "text": "cardText",
            "cardSubText": "4.3",
            "cardSubIcon": "favorites.png"
          },
          {
            "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "badges": [
              {
                "text": "badge1",
                "icon": "https://i.hizliresim.com/rawfdju.png"
              }
            ],
            "leftIcon": "icon1",
            "rightIcon": "icon2",
            "text": "cardText",
            "cardSubText": "4.3",
            "cardSubIcon": "favorites.png"
          }
        ]
      }
    },
    {
      "data": {
        "type": "3",
        "items": [
          {
            "image": "https://plus.unsplash.com/premium_photo-1679913792906-13ccc5c84d44?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "badges": [
              {
                "text": "badge1",
                "icon": "https://i.hizliresim.com/rawfdju.png"
              },
              {
                "text": "badge2",
                "icon": "https://i.hizliresim.com/2psw5ds.png"
              }
            ],
            "leftIcon": "icon1",
            "text": "cardText",
            "cardSubText": "4.5",
            "cardSubIcon": "favorites.png"
          },
          {
            "image": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=3560&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "badges": [
              {
                "text": "badge2",
                "icon": "https://i.hizliresim.com/2psw5ds.png"
              }
            ],
            "rightIcon": "icon2",
            "text": "cardText",
            "cardSubText": "3.0",
            "cardSubIcon": "favorites.png"
          },
          {
            "image": "https://images.unsplash.com/photo-1661523892046-c7ae3b169e13?q=80&w=3000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "badges": [
              {
                "text": "badge1",
                "icon": "https://i.hizliresim.com/rawfdju.png"
              }
            ],
            "leftIcon": "icon1",
            "rightIcon": "icon2",
            "text": "cardText",
            "cardSubText": "5.0",
            "cardSubIcon": "favorites.png"
          }
        ]
      }
    }
    ]
}
