{
  "tabs": [
    {
      "name": "Anlaşmalı Marketler",
      "sections": [
        {
          "type": "image",
          "data": [
            {
              "image": "url/to/banner/image.png",
              "text": "Anlaşmalı marketlerde anında %5 nakit iade!"
            }
          ]
        },
        {
          "type": "staticText",
          "data": {
            "text": "Ödeme yapacağınız anlaşmalı markayı seçin",
            "subText": "Depozito cüzdanınızdaki bakiye ile anlaşmalı noktalarda ve sanal pos cihazlarında karekod ile kolaylıkla ödeme yapabilirsiniz."
          }
        },
        {
          "type": "marketList",
          "data": [
            {
              "text": "A101",
              "subText": "5%",
              "image": "url/to/a101/logo.png",
              "actionUrl": "campaign/a101"
            },
            {
              "text": "Carrefour",
              "subText": "2%",
              "image": "url/to/carrefour/logo.png",
              "actionUrl": "campaign/carrefour"
            },
            {
              "text": "Çağrı Market",
              "subText": "5%",
              "image": "url/to/cagri/logo.png",
              "actionUrl": "campaign/cagri"
            },
            {
              "text": "Happy Center",
              "subText": "10TL",
              "image": "url/to/happycenter/logo.png",
              "actionUrl": "campaign/happycenter"
            }
          ]
        },
        {
          "type": "footer",
          "data": {
            "text": "Aradığınız marka listede yok mu?",
            "subText": "POS'ta Karekod ile Öde",
            "actionUrl": "payment/karekod"
          }
        }
      ]
    }
  ]
}
