{
  "tabs": [
    {
      "name": "Anlaşmalı Marketler",
      "sections": [
        {
          "data": {
            "type": "image",
            "items": [
              {
                "image": "url/to/banner/image.png",
                "text": "Anlaşmalı marketlerde anında %5 nakit iade!"
              }
            ]
          }
        },
        {
          "data": {
            "type": "marketList",
            "items": [
              {
                "text": "A101",
                "subText": "5%",
                "image": "url/to/a101/logo.png",
                "actionUrl": "campaign/a101"
              },
              {
                "text": "Carrefour",
                "subText": "2%",
                "image": "url/to/carrefour/logo.png",
                "actionUrl": "campaign/carrefour"
              },
              {
                "text": "Çağrı Market",
                "subText": "5%",
                "image": "url/to/cagri/logo.png",
                "actionUrl": "campaign/cagri"
              },
              {
                "text": "Happy Center",
                "subText": "10TL",
                "image": "url/to/happycenter/logo.png",
                "actionUrl": "campaign/happycenter"
              }
            ]
          }
        },
   {
          "data": {
            "type": "staticText",
            "content": {
              "text": "Ödeme yapacağınız anlaşmalı markayı seçin",
              "subText": "Depozito cüzdanınızdaki bakiye ile anlaşmalı noktalarda ve sanal pos cihazlarında karekod ile kolaylıkla ödeme yapabilirsiniz."
            }
          }
        },
        {
          "data": {
            "type": "footer",
            "content": {
              "text": "Aradığınız marka listede yok mu?",
              "subText": "POS'ta Karekod ile Öde",
              "actionUrl": "payment/karekod"
            }
          }
        }
      ]
    }
  ]
}
